### ISSUE TITLE
Failing XTR-utils functions

### ISSUE THREAD

**Issue by lorangedd** [spanikp/GNSS-toolbox#12]
Hi:
When I try to run the matlab code  , I got an error like this :

Error dataCell2matrix (line 3)
timeStamp = cellfun(@(c) datetime(c(9:27),'InputFormat','yyyy-MM-dd HH:mm:ss'),

 dataCell);

Wrong use of cellfun
The datetime output type is not supported. Please set'UniformOutput' to false.

How should I improve the code?

Thank you very much!

**Comment by spanikp** [comment]
OK, I see there 2 problems:
- on my machine with Matlab 2020b the script does not fail the way as it fail for you. What version of Matlab are you using? Maybe older version of Matlab differs in functionality for `datetime` function?
- anyway, for XTR file you provided it is not possible to plot MP, cycle-slip or SNR plots, since it does not contain such data. To fix this you need to run anubis again with different configuration option to set output to be more verbose. You can set it in configuration XML in `qc` element. This configuration works for me:
   - sec_sum="9"
    sec_hdr="9"
   sec_est="9"
   sec_obs="9"
   sec_gap="9"
   sec_bnd="9"
   sec_pre="9"
   sec_ele="9"
   sec_mpx="9"
   sec_snr="9"
   int_stp="600"
   int_gap="600"
   int_pcs="1800"
   mpx_nep="20"
   mpx_lim="3.0"
   col_sat="32"
   ele_cut="0"
   pos_kin="false"

**Comment by lorangedd** [comment]
My  matlab version is 2016a , so I agree with what you say , it is version a bug  . But is there another solution for me if I do not update my matlab ?

**Comment by lorangedd** [comment]
Have you ever tried to complie the anubis source code , I don't konw how to add input files.

**Comment by spanikp** [comment]
I could download Matlab version 2016a and try to debug on that version, but it will take some time.
I did build anubis on my own from source code. I am using Windows 10 and I did build in Windows Subsystem for Linux version 2 without problems.

**Comment by lorangedd** [comment]
I build my project using VS 2019 under Windows , but i am not familiar with C++ ,  so don't to know how to add input files like  rinex and xml file to debug . Can you give me some suggests ?

**Comment by spanikp** [comment]
I am not very familiar with C++ too :) And I am even less familiar with building C++ on Windows. I always go for Linux when it come to building from the source. Do you have opportunity to install Windows Subsystem for Linux (WSL)?
- if yes then follows https://docs.microsoft.com/en-us/windows/wsl/install-win10 or if that not work try to follow other tutorial how to install WSL on Windows 10 (Google will help you)
- if no I would suggest setup Linux virtual machine and perform anubis build there

**Comment by lorangedd** [comment]
Thank you very much . I think I can try it on my Linux virtual machine .

**Comment by spanikp** [comment]
In merge request #13 I did changes to make XTR utility functions running for R2016a. But you will need to provide XTR file with MP, SNR or Cycle slip data.

**Comment by lorangedd** [comment]
[AMC4200010.txt](https://github.com/spanikp/GNSS-toolbox/files/5861822/AMC4200010.txt)
I'm sorry to be late , how about the file AMC4200010.txt ?

**Comment by spanikp** [comment]
I checked the file AMC4200010.txt. It contains MP, SNR and cycle slip information, so it is possible to make plots you want on R2016a. However I has to make some fix due to fact that I primary made functions working with anubis files from RINEX v3 (file AMC4200010.txt was made of RINEX v2).

Now you can make the plots as following:
- switch on `dev` branch
- `addpath(genpath('Directory with GNSS-toolbox/src'))`
- create MP quantity skyplots: `xtr2MPskyplot('AMC4200010.txt','C1')`
- create SNR quantity skyplots: `xtr2SNRskyplot('AMC4200010.txt','S1')`
- create cycle slips skyplots: `xtr2CSskyplot('AMC4200010.txt')`

Note: I see that anubis you use is of version 2.2.4, but version 2.3 is already released. I suggest to update your anubis tool.

**Comment by lorangedd** [comment]
Thank you very much , I am excited to tell you I did it  . 
Also , I have updated my  anubis .
Thanks again ! May you all the best .

**Comment by spanikp** [comment]
I am happy we finally managed to run functions for your data successfully. Why did you reopened this issue? Is something missing or you got another error?

**Comment by lorangedd** [comment]
I am so sorry , I mistouch the button.
